# Generated by Django 3.2 on 2021-04-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('plus', 'Пополнение'), ('minus', 'Списание')], default='minus', max_length=5, verbose_name='Тип транзакции')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wallet', verbose_name='Кошелёк')),
            ],
        ),
    ]
